### ISSUE TITLE
how to decompress the http response with ecap ?

### ISSUE THREAD

**Issue by qianguozheng** [c-rack/squid-ecap-gzip#16]
I saw this project and found it just do the compress part, I am wondering how to do the decompress and add some script to the http response, but I don't know the procedure of the ecap well, could you please show me some samples? Thanks a lot.

**Comment by c-rack** [comment]
@qianguozheng all information you need to learn more about eCAP and HTTP GZIP compression is linked in the first sentence of the README:

> This is an [eCAP](http://www.e-cap.org/Home) adapter for [HTTP compression](https://en.wikipedia.org/wiki/HTTP_compression) with [GZIP](https://en.wikipedia.org/wiki/Gzip).

Just to make sure that I have understood your question correctly, you want to achive something like this?

`[upstream (compressed)] -> [squid (decompress)] -> [client (gets decompressed response)]`

**Comment by qianguozheng** [comment]
@c-rack  Yeah, it looks like that , to be detailed
`[upstream (compressed)] -> [squid(compressed)->ecap(decompress, insert script, compress)] -> client (gets compressed response)` or as you have said, just provide decompressed response is also fine. 

What trouble me is I don't know the ecap API executed procedure, and the sample modifying implement adaptConent(std::string &) while your source code doesn't implement that. 

Firstly I want to know ecap API call sequence. for example, when to call api adaptContent(std::string &) , after receive all the response ? or just part of that, the decompress method how to implement is the second priority, I can search on Internet, the major is about the ecap execute sequence.

Thanks in advance.

**Comment by c-rack** [comment]
This question is better asked here:
https://answers.launchpad.net/ecap

Feel free to close this issue with a link to your question there, so others can easily find it if they have the same use case, thanks.

**Comment by c-rack** [comment]
By the way, in the forum I mentioned there was already a similar question answered:
https://answers.launchpad.net/ecap/+question/273896

**Comment by qianguozheng** [comment]
@c-rack  Yeah, I have ask for help at there too, I found Alex have answered the sequence too, but not very familiar, anywhere thanks a lot, I will ask question there .
