### ISSUE TITLE
Have you encounter Squid memory continue increasing when enable ecap module ？

### ISSUE THREAD

**Issue by qianguozheng** [c-rack/squid-ecap-gzip#19]
I use ecap sample found this problem you can find the problem at this link.
https://answers.launchpad.net/ecap/+question/295319

**Comment by c-rack** [comment]
Is this fixed by #20?
If not, please reopen.

**Comment by yvoinov** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Yep, it fix memory leaking. Tested on two setups.

21.06.2016 21:59, Constantin Rack пишет:

> Is this fixed by #20 https://github.com/c-rack/squid-ecap-gzip/pull/20?
> If not, please reopen.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/c-rack/squid-ecap-gzip/issues/19#issuecomment-227486586,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOUiqKAGpe4GYTWU_s2Paj5fwKjdqXvTks5qOApSgaJpZM4I1-D5.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJXaWxdAAoJENNXIZxhPexGCAQIAIoY0xFOF25jaPv4BLNKS57K
pmfxG0b5VSH+EhN63nMW2XjyExZ1nweiG5k6SbczdVOc67Sif5kJmYh6Z+oJ+deZ
flNwE2iQJBv/AMjnkLNL0UMYU90qWTXfLjJ+M54ypD4nQEEum5oRy65k/iFbVNPd
nOtbe316eJ8gfOjWD7x0tj8l7v0rqdHXKbNsFGp6rBG/uYQ8XGufe0KRmAbL+V3w
2kuiflkSFFYsUEvxBvBOTSAIEC8I1g4wrE84kHskInAw7yzC+GOOCxqilgpBBtaq
pA3dM7OsUz0aYU/FyboWM+atPRIwoeKqX7HA+bvNhqnC1PETLJ60YTYGz2hYVaE=
=Xnse
-----END PGP SIGNATURE-----

**Comment by qianguozheng** [comment]
Yes, it is fixed.
